### ISSUE TITLE
Coloring is incomplete with nested braces

### ISSUE THREAD

**Issue by petdance** [vim-perl/vim-perl#120]
I'm finding that

```
@{$foo->{bar}}
```

and

```
%{$foo->{bar}}
```

do not colorize the final curly brace.

**EDIT** Example: ![screen shot 2013-06-07 at 4 58 49 pm](https://f.cloud.github.com/assets/107804/624307/a21c58d0-cf82-11e2-9340-9787bff79b28.png)

**Comment by jberger** [comment]
I still experience this bug when I use mojo.vim and `let mojo_highlight_data=1`.

I found some additional context here: https://github.com/yko/mojo.vim/issues/7

**Comment by hoelzro** [comment]
@jberger I just commented on that issue with a patch with (hopefully) a fix.

**Comment by jberger** [comment]
Thanks @hoelzro I hope it works!
