### ISSUE TITLE
Don't highlight ending heredoc markers in POD blocks

### ISSUE THREAD

**Issue by petdance** [vim-perl/vim-perl#14]
I have the following chunk of code:

```
=for when we get switching of instances working

    my $sql = <<'HERE';
        select ....
HERE

    my $row = sqldo_hashref( $sql ... );

=cut
```

and the closing HERE is highlighted.  It shouldn't be, because it's all comment in the POD.

**Comment by dkearns** [comment]
FWIW ten years later.

> @petdance Doesn't there need to be at least one leading space in front of the `HERE` in order for that to be included in part of the verbatim block?

No, verbatim blocks are started by a leading whitespace line but continue until the next blank line.

> The `=for` block trumps everything until the `=cut`.

`=for` only acts on the immediately following paragraph.

In this case `we get switching of instances working` is passed to the `when` formatter.  Then there's two verbatim paragraphs though some processors group consecutive paragraphs if it makes no difference.
