### ISSUE TITLE
Problems with highlighting/folding when using subroutine signatures

### ISSUE THREAD

**Issue by hoelzro** [vim-perl/vim-perl#166]
See https://github.com/vim-perl/vim-perl/pull/151#issuecomment-47777754 and https://github.com/vim-perl/vim-perl/issues/152#issuecomment-47776360

**Comment by zdm** [comment]
Seems, that this issue can be closed too.

**Comment by markjreed** [comment]
Ok, ran 'make install` with no preexisting .vimrc or .vim directory, turned highlighting on, and function signature parameters still show up highlighted in red, even with `let perl_no_subprototype_error=1`.  Using head of master as of today (2015-12-16). What am I doing wrong?

**Comment by zdm** [comment]
let perl_sub_signatures = 1

**Comment by markjreed** [comment]
Ah!  Thanks!

**Comment by wesQ3** [comment]
Should this issue be closed?

**Comment by hoelzro** [comment]
Seems so!
