### ISSUE TITLE
Method signatures show as errors

### ISSUE THREAD

**Issue by cubabit** [vim-perl/vim-perl#172]
I have copied method-signatures vim file to after folder, as per the instructions, but method signatures appear as errors in my instance of MacVim:

![screen shot 2015-01-18 at 16 31 20](https://cloud.githubusercontent.com/assets/307829/5793102/b3215d3c-9f2f-11e4-9dcf-b2db701641ce.png)

In fact no signatures apart from classic perl prototypes work.

Version of vim-perl:

    ~/.v/b/vim-perl (master) git show HEAD
    commit 2d87000ea7575fec94da8c595a0fdbb9c8f6cd63
    Author: Rob Hoelz <rob@hoelz.ro>
    Date:   Tue Dec 16 22:06:36 2014 -0600

        Add simple timing script

Here is my after folder:

    ~/.v/b/vim-perl (master) tree after
    after
    └── syntax
        └── perl
            ├── method-signatures.vim
            └── moose.vim

My version of MacVim (installed via brew):

    ~/.v/b/vim-perl (master ☡+) ls -l /usr/local/bin/gvim
    lrwxr-xr-x  1 pete  admin  34  3 Dec 10:59 /usr/local/bin/gvim -> ../Cellar/macvim/7.4-73_1/bin/gvim

**Comment by hoelzro** [comment]
Did you set `perl_no_subprototype_errors` in your vimrc?

**Comment by cubabit** [comment]
No - should I do this? If I do it says

    E518: Unknown option: perl_no_subprototype_errors

**Comment by hoelzro** [comment]
It's a variable, not an option, so you have to use `let`,  not `set`!

**Comment by cubabit** [comment]
Great - that fixed it. Sorry - my vim-fu is not very good! Perhaps the documentation could be made a little clearer though :)

**Comment by hoelzro** [comment]
I won't argue there =) I'll make a separate issue about improving the docs.

**Comment by hoelzro** [comment]
ah, we have one: #161
