### ISSUE TITLE
[Perl 5 & 6]: Incorrect Operators Highlighting

### ISSUE THREAD

**Issue by phongvcao** [vim-perl/vim-perl#182]
I was trying to code some small Perl script today and found out that the syntax highlighting for Perl 5 (maybe even Perl 6) is wrong for my case:

![selection_001](https://cloud.githubusercontent.com/assets/874795/6810895/70754aa0-d23a-11e4-8143-bb6da2c87800.png)

So basically the wrong syntax highlighting is caused by the (-M $file) and (-s $file) operators which return the $fileAge and $fileSize of the $file, respectively. After commenting out the 2 lines: 

my $fileAge = -M $file;
my $fileSize = -s $file;

then vim-perl syntax highlighting was working again. I hope you guys would fix this error soon since these 2 operators are quite common in Perl scripting.

**Comment by hoelzro** [comment]
@phongvcao Thanks for the bug report!  I just tried this on Git HEAD (457177c), and the highlighting seems to work fine.  Which `perl_*` options are you setting to configure vim-perl's behavior?  What version of Vim and vim-perl are you using?

**Comment by phongvcao** [comment]
@hoelzro I use non of the perl_* options. I am using Vim 7.4 (Patches 1-663) on Arch Linux x86_64

**Comment by hoelzro** [comment]
@phongvcao And which version of vim-perl are you using?

**Comment by phongvcao** [comment]
@hoelzro Oh you know what I think this bug is not because of vim-perl but because of the Valloric/vim-operator-highlight plugin (https://github.com/Valloric/vim-operator-highlight) I am using. After removing Valloric/vim-operator-highlight, everything was working again. I will report this bug there then.

Thanks for your support!

**Comment by hoelzro** [comment]
@phongvcao Happy to help!
