### ISSUE TITLE
"#" in < ... > construct treated like comment

### ISSUE THREAD

**Issue by rjbs** [vim-perl/vim-perl#188]
The `#` does not start a comment in `<...>` or `<<...>>`, but syntax makes it seem to.

```perl6
> < a b # c d >
a b # c d
> << a b # c d >>
a b # c d
```

**Comment by hinrik** [comment]
First of all, in the code you pasted, no `<...>` is getting string highlighting. Although if I remove the first character in the example (`>`) the `<...>` on the first line gets highlighted as a string, and the `#` inside it does not get highlighted as a comment. So I see no issue there. Do you see anything different? If so, are you running an older version of the syntax file?

As for the `<<...>>`, I do indeed see the `#` inside it highlighted as a comment. Rakudo doesn't support it, but I was going by [S02](http://design.perl6.org/S02.html) when I implemented it:

> Colon pairs (but not arrow pairs) are recognized within double angles. In addition, the double angles allow for comments beginning with #. These comments work exactly like ordinary comments in Perl code.

See also some `todo` tests in roast: https://github.com/perl6/roast/blob/master/S02-literals/quoting.t#L244-250

**Comment by rjbs** [comment]
I just updated to master, which was a small change.  Still I see the comment:

![1___no_name____-_vim](https://cloud.githubusercontent.com/assets/30682/7784234/7b4db202-012c-11e5-98f2-bf49345f1136.png)

**Comment by rjbs** [comment]
I must have had an older version, or perhaps it was fixed since I posted, since I'm pretty sure I updated then…

Thanks!
