### ISSUE TITLE
Perl 6 heredocs using additional adverbs are not highlighted as heredocs

### ISSUE THREAD

**Issue by hoelzro** [vim-perl/vim-perl#189]
Heredocs using additional adverbs (in my example, `:!closure`) are not highlighted as heredocs.
![heredoc-highlighting](https://cloud.githubusercontent.com/assets/107804/8533191/02f0c836-23f9-11e5-900c-d84a3e9d1933.png)

Source:
```perl6
say q:!closure:to/END_HERE/;
shouldn't
be
highlighted
as
Perl 6
END_HERE
```

My vimrc: https://github.com/hoelzro/vimfiles

My Vim version: 7.4.764

**Comment by hinrik** [comment]
Fixed this with bf1c235.
