### ISSUE TITLE
syntax perl.vim: Issue with here-doc containing quotes mark (single or double)

### ISSUE THREAD

**Issue by krime** [vim-perl/vim-perl#198]
When I leave don't, can't, doesn't these words within here-doc, which will broke the syntax match after the quotes.
```sh
print $fh << EOF;
  I really don't know this.
EOF
```

**Comment by hoelzro** [comment]
@krime If you remove the space between `<<` and `EOF`, things highlight correctly.  Having a space in there isn't valid Perl, as far as I know.

**Comment by hoelzro** [comment]
@krime Did I address your issue?  Or did I misunderstand something?

**Comment by hoelzro** [comment]
Since this seems to not actually be a bug, I'm going to go ahead and close it.  If I'm mistaken, please feel free to reopen!
