### ISSUE TITLE
problem recognizing chained method call

### ISSUE THREAD

**Issue by y** [vim-perl/vim-perl#200]
at_midnight isn't recognized as a method in the following. The `(1)` is throwing off the recognition.

```
$now->plus_days(1)->at_midnight;
```

**Comment by hoelzro** [comment]
Screenshot on 456b3e2:

![vim-perl](https://cloud.githubusercontent.com/assets/107804/10820133/be18b680-7e19-11e5-88d5-698aae96bd68.png)

**Comment by hinrik** [comment]
Yeah, chained method calls have never been highlighted. The highlighting also doesn't apply when there's any space in between, even though this is valid in Perl:

![method](https://cloud.githubusercontent.com/assets/43533/10822168/53f428f6-7e56-11e5-8767-010bf95ba382.png)

**Comment by hoelzro** [comment]
Is this Not a Bug, then?

**Comment by hinrik** [comment]
There are some inconsistencies in the highlighting, so I'd say it's a bug. I'll take a look at it soon.

**Comment by hoelzro** [comment]
Related: #218

**Comment by y** [comment]
I took a stab at it got it to recognize chained method calls and extra whitespace, but it causes some tests to fail. Maybe someone who actually understands vim syntax highlighting can fix it up:
https://github.com/y/vim-perl/commit/7e9dd611d361f8aae26a6e47423a28d8bcb27289

**Comment by hoelzro** [comment]
@y Thanks for giving that a try - I'm beginning to question the wisdom of highlighting method calls entirely, though.  I would rather not highlight method calls at all (or fix chained method calls) than have a highlighting that works inconsistently.  I'm personally leaning towards removing method call highlighting, since 1) I don't personally care for it 2) it's less work to add and maintain proper highlighting if method call highlighting is removed and 3) it will simplify and potentially speed up highlighting.  How do you feel about the prospect of removing method call highlighting?

**Comment by hoelzro** [comment]
@y That's a good idea!

**Comment by hoelzro** [comment]
Please offer an emoji response to this comment to indicate your vote for how to proceed:

  * 1️⃣  (`:one:`) for "keep things as they are"
  * 2️⃣  (`:two:`) for "simplified highlighting"
  * 3️⃣  (`:three:`) for "fixed, more complicated highlighting"

**Comment by petdance** [comment]
:two:

**Comment by hoelzro** [comment]
@mbudde pointed out this bug with my experimental branch: https://github.com/vim-perl/vim-perl/commit/587b1d0710916d0fdff14f8212dcd5279ad13406#commitcomment-24367132

**Comment by mcsnolte** [comment]
:two:

**Comment by clonezone** [comment]
:3:, where arrows and parens get a different syntax class than the method name.

**Comment by AndyColson** [comment]
2️⃣

**Comment by sjohnston** [comment]
:three:, where arrows and parens get a different syntax class than the method name.

**Comment by rollor** [comment]
3️⃣. Make all complicated options optional and the default case should be indistinguishable from :two:.

**Comment by Smylers** [comment]
:two:

I always thought it weird that method names (sometimes) are in the same colour as variable names, not as function names. Or indeed as class methods, which also retain the default colouring.

Stopping trying to colour method names will make this all consistent, which is way more useful in syntax highlighting.

**Comment by derobert** [comment]
3️⃣

**Comment by vadz** [comment]
:two: but maybe still give a separate class to the arrows to allow highlighting them if desired?

**Comment by gowther-zoho** [comment]
simplified highlighting

I don't feel the emoji.

**Comment by nfg** [comment]
:two:

**Comment by jiyyt** [comment]
:two:

**Comment by neilb** [comment]
2️⃣

**Comment by Grinnz** [comment]
:two: Don't use vim, but the rules for highlighting a method chain properly would be incredibly complicated given what is possible to give as method arguments.

**Comment by cees** [comment]
:two:

**Comment by ap** [comment]
2️⃣

**Comment by heikojansen** [comment]
:two:

**Comment by fffinkel** [comment]
:two:

**Comment by trwyant** [comment]
:two: Why highlight a method chain of any length differently than a subroutine call?

**Comment by mmcclimon** [comment]
3️⃣

**Comment by batlock666** [comment]
:two:

**Comment by merrilymeredith** [comment]
:two:

I just want it consistent, and the current highlighting also breaks if you have newlines in your method chain to look this way after the newline anyway.  Performance and maintenance also A-OK!

**Comment by rba** [comment]
2️⃣

**Comment by Camspi** [comment]
:two:

**Comment by mannih** [comment]
2️⃣

**Comment by borisdaeppen** [comment]
:two: because consistency, if :three: has the drawbacks mentioned

**Comment by mikkoi** [comment]
:two:

**Comment by simongreen-net** [comment]
(:two:)

**Comment by chsanch** [comment]
2️⃣

**Comment by mrallen1** [comment]
2️⃣

**Comment by dnebauer** [comment]
:two:

**Comment by abraxxa** [comment]
:three:, where arrows and parens get a different syntax class than the method name.

**Comment by hoelzro** [comment]
Ok, it's been a week now - it looks like the "simplified highlighting" folks have it.  We can start working on making the syntax highlighting simpler and more consistent soon.

**Comment by jwittkoski** [comment]
:three:, where arrows and parens get a different syntax class than the method name.

**Comment by hoelzro** [comment]
That being said, I would look at a PR implementing  3️⃣  behind an opt-in option, as suggested [here](https://github.com/vim-perl/vim-perl/issues/200#issuecomment-330271552).

**Comment by ivanwills** [comment]
2️⃣ It is better to be simple, clean and fast

**Comment by chazubell** [comment]
![image](https://user-images.githubusercontent.com/132474/30835289-72532226-a20c-11e7-8cf5-7e11df694a41.png)

**Comment by sverrewl** [comment]
:2:

**Comment by bewuethr** [comment]
:three:

**Comment by elohmrow** [comment]
(:two:)

**Comment by gs230937207** [comment]
:two:

**Comment by gwadej** [comment]
:two:

**Comment by hoelzro** [comment]
Ok, I've implemented :two: and pushed that into the dev branch. If you run into any issues with the change, please file a separate isssue.  If anyone would like to take a crack at implementing :three:, feel free to reach out!
