### ISSUE TITLE
Enabling g:perl_fold_anonymous_subs disables regular perl sub folding

### ISSUE THREAD

**Issue by cazador481** [vim-perl/vim-perl#203]
Enabling g:perl_fold_anonymous_subs disables regular perl sub folding

The fix is easy:  remove the else statement around the folding for non anonyous_subs

**Comment by hoelzro** [comment]
@cazador481 Do you have an example of this?  I've been using `perl_fold_anonymous_subs` for a long time, and I've never seen it interfere with regular folding.

**Comment by cazador481** [comment]
Closing issue, as it started working after I reinstall neovim.
