### ISSUE TITLE
Set makeprg and errorformat

### ISSUE THREAD

**Issue by harleypig** [vim-perl/vim-perl#21]
If makeprg and errorformat are set, you can use the ]c and [c commands to find syntax errors:

setlocal errorformat=%f:%l:%m
setlocal makeprg=perl\ -c\ %\ $*

**Comment by sigzero** [comment]
Was there a yay or nay on this issue?

**Comment by petdance** [comment]
I'm OK with making the make cycle quicker.  I don't use that functionality in vim, so someone else will need to code and vet it.

**Comment by dkearns** [comment]
This is a duplicate of #128 or vice versa and fixed via #129.

I have contacted the maintainer of `compiler/perl.vim` about inclusion in this project.
