### ISSUE TITLE
xs syntax hilighting c functions as errros

### ISSUE THREAD

**Issue by y** [vim-perl/vim-perl#211]
C functions are being hilighted as errors. See schmorp's blog entry here for details:
http://blog.schmorp.de/2016-01-24-tidbits-fixing-vim-xs-syntax-highlighting.html

**Comment by hoelzro** [comment]
I believe this was done deliberately; functions provided by libc aren't necessarily consistent in their implementation, so XS provides things like `Copy` instead of `memcpy`, and XS authors are encouraged to use those.

**Comment by hoelzro** [comment]
I have just updated `xs.vim` so that this is off by default, though; if users want to turn it back on, they can set `xs_superseded=1` in their vimrc.

**Comment by petdance** [comment]
Please be sure to note it in the change log.

**Comment by hoelzro** [comment]
@petdance Already done!
