### ISSUE TITLE
Perl5 subs folding work incorrectly

### ISSUE THREAD

**Issue by zdm** [vim-perl/vim-perl#220]
# Description of issue

Perl5 subs folding works incorrectly, when subroutine contains slice.
# Screenshot of the issue:

unfolded:
![screenshot 2016-05-13 09 15 18](https://cloud.githubusercontent.com/assets/1025608/15239469/72afea34-18eb-11e6-98b7-b7841866b907.png)

folded:
![screenshot 2016-05-13 09 15 23](https://cloud.githubusercontent.com/assets/1025608/15239472/7acafbdc-18eb-11e6-9881-ef316eaebe50.png)
# Sample code:

``` perl

sub add_domain_filter ( $self, $domain_filter ) {
    my $index = {};

    $index->@{ $DOMAIN_FILTER->@*, $domain_filter->@* } = ();

    return;
}
```
# Link to vimrc

let perl_sync_dist = 250
let perl_fold = 1
let perl_fold_anonymous_subs = 1
let perl_nofold_packages = 1
let perl_include_pod = 1
let perl_sub_signatures = 1

[vimrc](...)
# Output of `vim --version`

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 11 2016 22:23:44)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1830
Compiled by zdm@ZDM-X1-CARBON
Huge version with GUI.  Features included (+) or not (-):
+acl                +eval               +mouseshape         +tag_old_static
+arabic             +ex_extra           +multi_byte_ime/dyn -tag_any_white
+autocmd            +extra_search       +multi_lang         -tcl
+balloon_eval       +farsi              -mzscheme           -termguicolors
+browse             +file_in_path       +netbeans_intg      -tgetent
++builtin_terms     +find_in_path       +ole                -termresponse
+byte_offset        +float              +packages           +textobjects
+channel            +folding            +path_extra         +timers
+cindent            -footer             +perl/dyn           +title
+clientserver       +gettext/dyn        +persistent_undo    +toolbar
+clipboard          -hangul_input       +postscript         +user_commands
+cmdline_compl      +iconv/dyn          +printer            +vertsplit
+cmdline_hist       +insert_expand      +profile            +virtualedit
+cmdline_info       +job                -python             +visual
+comments           +jumplist           -python3            +visualextra
+conceal            +keymap             +quickfix           +viminfo
+cryptv             +langmap            +reltime            +vreplace
+cscope             +libcall            +rightleft          +wildignore
+cursorbind         +linebreak          -ruby               +wildmenu
+cursorshape        +lispindent         +scrollbind         +windows
+dialog_con_gui     +listcmds           +signs              +writebackup
+diff               +localmap           +smartindent        -xfontset
+digraphs           -lua                +startuptime        -xim
+directx            +menu               +statusline         -xterm_save
-dnd                +mksession          -sun_workshop       +xpm_w32
-ebcdic             +modify_fname       +syntax  
+emacs_tags         +mouse              +tag_binary  
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM_vimrc"
      user exrc file: "$HOME_exrc"
  2nd user exrc file: "$VIM_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM_gvimrc"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: gcc -Iproto -DWIN32 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF 
-DFEAT_HUGE -DMS_WIN64 -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DMSWINPS 
-DFEAT_OLE -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_DIRECTX 
-DDYNAMIC_DIRECTX -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME 
-DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=x86-64 -Wall -Id:/devel/perl/perl/lib/Core -DFEAT_PERL 
-DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL="perl522.dll" 
-DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 -fomit-frame-pointer -freg-struct-return -s
Linking: gcc -Iproto -DWIN32 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF -DFEAT_HUGE 
-DMS_WIN64 -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DMSWINPS -DFEAT_OLE 
-DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_DIRECTX -DDYNAMIC_DIRECTX 
-DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME 
-DDYNAMIC_ICONV -pipe -march=x86-64 -Wall -Id:/devel/perl/perl/lib/Core -DFEAT_PERL 
-DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL="perl522.dll" 
-DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 -fomit-frame-pointer -freg-struct-return -s 
-mwindows -o gvim.exe -lkernel32 -luser32 -lgdi32 -ladvapi32 -lcomdlg32 -lcomctl32 -lversion -lwsock32 -ld2d1 
-ldwrite -Lxpm/x64/lib -lXpm -loleaut32 -Wl,-Bstatic -lstdc++ -Wl,-Bdynamic -lole32 -luuid

**Comment by hoelzro** [comment]
Thanks for the fix @zdm! This should be working now.
