### ISSUE TITLE
perl 5.28 sub attributes and signatures problem

### ISSUE THREAD

**Issue by zdm** [vim-perl/vim-perl#260]
# Description of issue
In perl 5.28 sub attributes were moved before signature. Currently hl and fold works incorrectly in this case.

# Sample code:

```perl
sub aaa : prototype($$) ($a, $b) {
    return;
}
```
# Link to vimrc
```
let perl_sync_dist = 250
let perl_fold = 1
let perl_fold_anonymous_subs = 1
let perl_nofold_packages = 1
let perl_include_pod = 1
let perl_sub_signatures = 1
```

# Output of `vim --version`
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 10 2018 06:43:38)
Included patches: 1-173
Compiled by mockbuild
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vartabs
-clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         -python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               -ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo  -ldl
```

**Comment by hoelzro** [comment]
Thanks for the report @zdm - we'll dig into this!

**Comment by zdm** [comment]
Actually the conflict is with line 67: 
```
syn region perlBraces start="{" end="}" transparent extend
```
If I comment it - folds works.

**Comment by zdm** [comment]
I think, we should use "keepend" instead of "extend":
```
syn region perlBraces start="{" end="}" transparent keepend
```
But I don't know what side effects this will bring.
Syntax file is pretty complex.
Could you clarify, please?

**Comment by hoelzro** [comment]
Interesting suggestion @zdm - unfortunately, when I made this change and ran the test suite, it breaks folding of anonymous subs.  I'm kind of in the middle of another personal project right now, and I can never remember exactly what `keepend` and `extend` do, so I'll get around to this when I can.

Off the top of my head, I would guess that a proper fix would be in this part of `syntax/perl.vim`:

https://github.com/vim-perl/vim-perl/blob/1b83c8499ff14bfa5b5fe5bfb09dd75f77c3ac6d/syntax/perl.vim#L384-L399

> Syntax file is pretty complex.

Don't I know it =(

I wish we could clean it up and simplify it - maybe that would enable more people to contribute? Just thinking out loud here.

**Comment by zdm** [comment]
Yes, you are right, my previous suggestions was wrong.
I am almost done with the patch.
Give me 2 hours.

**Comment by zdm** [comment]
here is the updated syntax script
folding and highlight fixed, attributes works regardless of the position, before or after signature.
+ some improvements, for example support for multiline sub declaration.
[1.zip](https://github.com/vim-perl/vim-perl/files/2193603/1.zip)

**Comment by zdm** [comment]
I created pull request, not sure, that I did it correctly, I am bitbucket user.

**Comment by hoelzro** [comment]
Thanks! I'll look at the PR later!

**Comment by petdance** [comment]
Let's make sure that we check to see if there are any slowdowns from this change.

**Comment by zdm** [comment]
Also this PR closes issue #220

**Comment by hoelzro** [comment]
Ok, this should be fixed now.

**Comment by zdm** [comment]
@hoelzro 
Folding and syntax hl still works incorrectly for this piece of the code:
```

sub asas::asdsad::adsa : prototype() : lvalue : method ($d) {    # adasdsad
    return;
}

sub asdsad : prototype() : lvalue
  : method($d) {                                                 # adasdsad
    my $s = sub : prototype($$) ( $a, $v ) {
        return;
    };

    return;
}
```

**Comment by hoelzro** [comment]
@zdm Thanks for letting me know; I'll patch that up when I have a chance.

**Comment by hoelzro** [comment]
@zdm I fixed your example, with one small modification - I put the second method definition all on a single line.  I can't easily make the multi-line form work without breaking other highlighting, and I need to take some time to figure out how to make that work.

**Comment by zdm** [comment]
You can use my pull request ;-)

Believe me, no one requires to highlight errors in subroutines
definition, this is absolutely useless feature.

Why you decided to highlight wrong brackets only in sub signatures? If
you want to follow this logic - you need to highlight all perl syntax
errors, that is impossible.

**Comment by hoelzro** [comment]
@zdm I see your point about removing the highlighting of subroutine errors, especially with signatures in Perl.  However, your PR fails the test suite, and the failures I'm seeing aren't related to error highlighting - rather, they're related to forward declarations and how those are handled with highlighting and folding.  Here's an example of one of the failures the test suite picked up:

![vim-perl-pr-262-highlight-failures](https://user-images.githubusercontent.com/107804/43408059-00458a30-93e6-11e8-9691-e3aff119970a.png)

This is the same issue I ran into when I tried to fix your multi-line example that I mentioned in https://github.com/vim-perl/vim-perl/issues/260#issuecomment-408857657 ; if you have any ideas on how we can fix that issue, I would really appreciate the help!

**Comment by zdm** [comment]
I will check tomorrow.

**Comment by zdm** [comment]
Pls, try new PR.

**Comment by zdm** [comment]
+ I added new option g:perl_fold_do_blocks, it allows to fold only do blocks.
