### ISSUE TITLE
Indent after sub disabled

### ISSUE THREAD

**Issue by yjfguhd** [vim-perl/vim-perl#267]
# Description of issue

When entering "sub foo {\<cr>", the cursor is placed at the beginning of the line, like so (with "|" indicating the cursor):
```perl
sub foo {
|
```
Behaviour previous to commit a998ba40d0ff38b18c23c52efac976d104052fbc would have indented the cursor, like so:
```perl
sub foo {
        |
```
It appears that syntax/perl.vim:390 has changed Vim to effectively ignore the indentation size given by shiftwidth. Commenting out that line fixes the missing indentation.

The demonstration above was done with a new user (so, no personal Vim setup at all), and a clone of this repository into `~/.vim/`.

# Output of `vim --version`
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 27 2018 13:29:35)
Included patches: 1-498
Compiled by paul@sulaco
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               -perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         -python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               -ruby              +writebackup
+dialog_con_gui    +menu              +scrollbind        +X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       +xpm
-ebcdic            +mouseshape        +statusline        +xsmp_interact
+emacs_tags        +mouse_dec         -sun_workshop      +xterm_clipboard
+eval              +mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -march=amdfam10 -O2 -pipe -fomit-frame-pointer -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl  -lacl -lattr -lgpm -ldl
```

**Comment by hoelzro** [comment]
@yjfguhd Thanks for the report! I'm having trouble reproducing it, but I'll keep at it.

**Comment by yjfguhd** [comment]
Maybe [this video](https://asciinema.org/a/Fg1VHuW6Dn3UpF6k4CwcYveQv) will help. In it, I first demonstrate the default behaviour with no Vim config, where the indentation is fine. Then, I show the same procedure when using vim-perl.

**Comment by hoelzro** [comment]
Thanks for the video!  I guess I should've been more clear - I'm not seeing the indentation happening, regardless of whether or not I have something from before `a998ba4`.

**Comment by yjfguhd** [comment]
Perhaps you're using a version of Vim prior to 7.4.2111, which introduced defaults.vim, which gets sourced automatically if there is no user vimrc. In that case, you'll be missing `filetype plugin indent on`, so try that command before opening a Perl filetype (it should be good enough to have it in your vimrc).

**Comment by hoelzro** [comment]
I didn't know about `defaults.vim` - good call on that!  Sourcing that reproduces the issue.

**Comment by mannih** [comment]
Hate to say so, but: this affects me as well.

**Comment by sdondley** [comment]
I have version 8 with `filetype plugin indent on` explicitly turned on in my .vimrc and I'm seeing this issue.

**Comment by sdondley** [comment]
OK, I had `vim` aliased to `nvim` on my machine. After turning that off, the indentation works fine.

**Comment by hoelzro** [comment]
@sdondley Are you saying this issue happens with neovim only?

**Comment by sdondley** [comment]
I can't say for sure. Here's what I know:

1) If both the `cindent` and `smartindent` settings are off, indentation doesn't work in regular vim. You have to have one of these turned on.
2) I could not get indentation for `sub` functions working in neovim at all, regardless what the state of these two settings were, without resorting to hacking the vim-perl syntax file. So that tells me neovim was recognizing indenting, but the syntax file was messing with neovim's ability to detect when it should indent and when it should not.
3) Folding seemed be totally hosed using neovim with the newest version vim-perl installed in my local files. With the stock perl.vim provided by regular vim, things worked reasonably well.

I should also add that I installed vim-perl files in my local `.vim` directory. I left the stock */perl.vim files in both vim and neovim directories. I'm not sure if this is OK or not.

**Comment by sdondley** [comment]
Oh, also just remembered that in my `.vimrc` I had `filetype plugin indent on` in there. That actually broke things for me in regular vim. If I change that to just plain `filetype plugin on`, indentation works again.

**Comment by sdondley** [comment]
So, I just did `nvim test.pl` and to see if indentation worked with `sub`. It did not. Then I did `vim test.pl`. Things worked perfectly. So with the same exact same vim configuration, vim works, nvim doesn't.

Note: I have neovim set up with vim with `ln -s ~/.vimrc ~/.config/nvim/init.vim`

**Comment by sdondley** [comment]
Well, guess I'm going to have to live with the nvim bug. Vim is almost unusable. It's so slow compared to neovim. I'm using a vim scripting hack to get around the issue for now with a plugin Damian Conway wrote called smartcom, for "smart completion."

**Comment by hoelzro** [comment]
Ok, thanks for taking the time to investigate!  I'm wondering if this is related to the defaults.vim issue mentioned [here](https://github.com/vim-perl/vim-perl/issues/267#issuecomment-433656488)

**Comment by happy-dude** [comment]
I just wanted to give this issue a poke and mention that I believe this still affects the latest (HEAD) versions of vim (8.2.2488) and neovim (v0.5.0-dev+nightly-455-g971e0ca90).

Is the issue of not auto-indenting after `if (..) {` braces related?

**Comment by petdance** [comment]
I don't have any progress.

**Comment by mbudde** [comment]
I have tested Vim 8.2 and Neovim 0.4.4 using this config:
```
syntax on
filetype plugin indent on
set rtp=~/.local/share/nvim/plugged/vim-perl
```
In both editors the indentation is incorrect after `sub foo {`. The brace gets a `synid` value of `perlSubDeclaration`. Adding the following change to `indent/perl.vim` seems to fix the indentation in both editors:
```diff
diff --git a/indent/perl.vim b/indent/perl.vim
index 19f03e3..6bef35c 100644
--- a/indent/perl.vim
+++ b/indent/perl.vim
@@ -131,6 +131,7 @@ function! GetPerlIndent()
                         \ || synid == "perlHereDoc"
                         \ || synid == "perlBraces"
                         \ || synid == "perlStatementIndirObj"
+                        \ || synid == "perlSubDeclaration"
                         \ || synid =~ "^perlFiledescStatement"
                         \ || synid =~ '^perl\(Sub\|Block\|Package\)Fold'
                 let brace = strpart(line, bracepos, 1)
```

**Comment by vitahall** [comment]
I noticed this problem after installing commit 0f4b88b (current vim-perl/master as of 2022-01-30). After making the change given by @mbudde indentation is now working as I expect, and as it did with the perl-vim that shipped with Vim 8.2 on Debian 11 "Bullseye".

**Comment by yjfguhd** [comment]
> Adding the following change to `indent/perl.vim` seems to fix the indentation in both editors:
> 
> ```diff
> diff --git a/indent/perl.vim b/indent/perl.vim
> index 19f03e3..6bef35c 100644
> --- a/indent/perl.vim
> +++ b/indent/perl.vim
> @@ -131,6 +131,7 @@ function! GetPerlIndent()
>                          \ || synid == "perlHereDoc"
>                          \ || synid == "perlBraces"
>                          \ || synid == "perlStatementIndirObj"
> +                        \ || synid == "perlSubDeclaration"
>                          \ || synid =~ "^perlFiledescStatement"
>                          \ || synid =~ '^perl\(Sub\|Block\|Package\)Fold'
>                  let brace = strpart(line, bracepos, 1)
> ```

This indeed fixes it in Vim 8.2.4221.

**Comment by y** [comment]
That fixes the problem for me also. Does someone have to actually make a pull request to get this updated?

**Comment by petdance** [comment]
No, we just need to have the time to get to it. I'll add it to my to-do list.

**Comment by petdance** [comment]
I've applied this.  Thanks y'all.  5bca914
