### ISSUE TITLE
Documentation for fold options

### ISSUE THREAD

**Issue by srchulo** [vim-perl/vim-perl#269]
# Description of issue

From this issue:

https://github.com/vim-perl/vim-perl/issues/251

I found fold options that I didn't know existed, and I can't seem to find them anywhere in the README. Would it be possible to add some documentation around what's possible? Is there any other documentation for other features that may be missing?

**Comment by dkearns** [comment]
There's documentation provided with Vim.

`:help perl.vim`

**Comment by petdance** [comment]
I think adding a bullet list of features to the README.md would be a good idea.

**Comment by petdance** [comment]
@srchulo Can you say more please about what options you found that weren't documented?  What can we put in the README that would help future users like yourself?
