### ISSUE TITLE
Putting yanked code auto indents backwards

### ISSUE THREAD

**Issue by srchulo** [vim-perl/vim-perl#272]
# Description of issue

If I have a sub like so:

```
sub foo {
    my ($bar) = @_;
    say "$bar";
}
```

If I go into visual mode, go over all of it, yank, and then put it with `p`, the code puts correctly initially, and then all of the code auto indents back to the start of the line like so:

```
sub foo {
my ($bar) = @_;
say "$bar";
}
```

If your bug is not related to highlighting or folding, please feel free
to delete the text below.

Commenting out vim-perl fixes this issue.

# Link to vimrc

[vimrc](https://gist.github.com/srchulo/ce98e83d3c4ce715e03af02f0cd114a9)

# Output of `vim --version`
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 24 2018 21:29:04)
Included patches: 1-1522
```

**Comment by hoelzro** [comment]
Hello, and thanks for the report!  This is going to be a bit hard to golf down, but I imagine [this line](https://gist.github.com/srchulo/ce98e83d3c4ce715e03af02f0cd114a9#file-vimrc-L124) in your vimrc has something to do with what's going on.  Would you mind filling us in with what `equalprg` and `indentexpr` are set to?  You can find out by running `:set equalprg?` and `:set indentexpr?`

**Comment by srchulo** [comment]
Hey, so I'm sorry about that. Commenting out those lines did the fix-- I'm actually not sure what those were there for! I thought it was vim-perl, since commenting that out fixed it. For completeness, here are my values for those:

`equalprg=`
And
` indentexpr=GetPerlIndent()`

Please feel free to close! Thanks for the help :)
