### ISSUE TITLE
Hackathons in 2022

### ISSUE THREAD

**Issue by djzort** [vim-perl/vim-perl#311]
I am uncertain what the best contact is for vim-perl so I just thought i would create an issue. 

We in the perl marketing committee would like to get this project involved in an IDE Hackathon in 2022 (see https://news.perlfoundation.org/post/hackothon-events-planning-2022)

Please comment on the above post and/or jump in to the marketing channel on The Perl Foundations Slack instance (perlfoundation dot slack dot com)

**Comment by petdance** [comment]
I don't see any marketing channel in the TPF Slack. Just #perl.

**Comment by rabbiveesh** [comment]
You need to go to add channel and find it there

**Comment by petdance** [comment]
There is nothing in Add Channel besides #perl.

**Comment by petdance** [comment]
Is this still something you're interested in pursuing? You can email me at andy@petdance.com if you like.

**Comment by djzort** [comment]
please pardon the delayed response. it seems your account there is a "guest" so i will have someone bump it

**Comment by djzort** [comment]
ok @petdance your account has been sorted and i have added you to the hackathon channel
