### ISSUE TITLE
Prep for 2022 Perl editor/IDE hackathton

### ISSUE THREAD

**Issue by petdance** [vim-perl/vim-perl#312]
@djzort is driving a [hackathon](https://news.perlfoundation.org/post/hackothon-events-planning-2022) and would like vim-perl to be involved. (See #311 for original issue)

Goals of this hackathon are:
* Drive improvements in IDE/editor support for Perl
* Encourage people to get involved who wouldn’t have before
* Add a page to perl.org to get people started in their favourite editor/IDE

I'm starting this issue here as a place for discussion about this.  We can also discuss in the #vim-perl channel on my beyondgrep.slack.com Slack.  Ask me for an invite.

What can we do to get people to start working in vim-perl? Are there beginner tasks we can create?

**Comment by djzort** [comment]
Just bumping this. You might want to tag issues for newbies etc?

**Comment by petdance** [comment]
I don't think there are any. Everything in vim-perl is pretty arcane.

**Comment by djzort** [comment]
I suggest closing this now.
