### ISSUE TITLE
Regression: spell checking no longer works in perlPOD in DATA section

### ISSUE THREAD

**Issue by grr** [vim-perl/vim-perl#314]
# Description of issue

Up until  commit 1ad98eee4ca9509fa89366085e3cb5ecf61c8f6f, spell checking would work in POD that was included in the DATA section. After that commit, spell checking no longer works in POD in the DATA section.
Also, when it did work, it apparently only worked if the DATA section was marked with `__END__` and didn't work if it was marked with `__DATA__`.

# Sample code:

```
__END__

=head1 NAME

Tiny::Fast - effffficiently compute stuff

=cut
```

# Link to vimrc

\# in ~/.vim/after/ftplugin/perl.vim
let g:perl_include_pod = 1
let g:perl_fold = 1
let g:perl_nofold_packages = 1
let g:perl_nofold_subs = 1
let g:perl_string_as_statement = 1

# Output of `vim --version`
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 12 2021 23:47:11)
macOS version - arm64
Included patches: 1-2683
Compiled by MacPorts
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
-cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/opt/local/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/opt/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -DMACOS_X -DMACOS_X_DARWIN -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -arch arm64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -arch arm64 -o vim -lm -lncurses -liconv -lintl -framework AppKit
```

**Comment by petdance** [comment]
Can you tell what specifically in the commit broke it?

@dkearns any ideas?

**Comment by dkearns** [comment]
I think the following will restore the old behaviour?

```patch
diff --git a/syntax/pod.vim b/syntax/pod.vim
index e6f8335..fec8915 100644
--- a/syntax/pod.vim
+++ b/syntax/pod.vim
@@ -43,7 +43,7 @@ syn match podForKeywd "\S\+" contained contains=@NoSpell
 " An indented line, to be displayed verbatim
 syn region podVerbatim start="^\s\+\S.*$" end="^\ze\s*$" end="^\ze=cut\>" contains=@NoSpell
 
-syn region podOrdinary start="^\S.*$" end="^\ze\s*$" end="^\ze=cut\>" contains=podFormat,podSpecial,@NoSpell
+syn region podOrdinary start="^\S.*$" end="^\ze\s*$" end="^\ze=cut\>" contains=podFormat,podSpecial,@Spell
 
 " Inline textual items handled specially by POD
 syn match podSpecial   "\(\<\|&\)\I\i*\(::\I\i*\)*([^)]*)" contains=@NoSpell
```

**Comment by grr** [comment]
> ```diff
> -syn region podOrdinary start="^\S.*$" end="^\ze\s*$" end="^\ze=cut\>" contains=podFormat,podSpecial,@NoSpell
> +syn region podOrdinary start="^\S.*$" end="^\ze\s*$" end="^\ze=cut\>" contains=podFormat,podSpecial,@Spell
> ```

Confirmed. That fixes it.

> Also, when it did work, it apparently only worked if the DATA section was marked with __END__ and didn't work if it was marked with \_\_DATA__

Found the issue here: #42. It looks like the change was made only because of personal preference. Most people think \_\_DATA__ and \_\_END__ are interchangeable and the documentation in perlpod makes no distinction here: https://perldoc.perl.org/perlpod#Embedding-Pods-in-Perl-Modules . there's also plenty of code on CPAN and the wild that has POD after a \_\_DATA__ section (google filetype:pm "\_\_DATA__ =head1")

**Comment by petdance** [comment]
Huh, I've never heard of anyone having POD in `__DATA__`, but clearly the docs say it's OK.  Thanks for the research.

**Comment by dkearns** [comment]
@petdance I have some significant changes to the Pod syntax file that also address spell checking but I haven't looked at them for a few months so I might not get to creating a PR until the end of next week.

Did you want to me make an intermediate one that fixes this and maybe addresses a couple of other simple spell-check issues?

**Comment by petdance** [comment]
> Did you want to me make an intermediate one that fixes this and maybe addresses a couple of other simple spell-check issues?

Yes, please.

**Comment by grr** [comment]
Bug has resurfaced again.

Tested against 9.1 in console vim and MacVim with no other plugins and minimal vimrc.

**Comment by dkearns** [comment]
Have you set the config variable `perl_highlight_data`?  It will only spell check it if it's being highlighted as POD in the DATA section.

**Comment by grr** [comment]
Thanks! That was my issue. Missed it when I checked the docs ;-)
