### ISSUE TITLE
Release for Vim 9

### ISSUE THREAD

**Issue by dkearns** [vim-perl/vim-perl#320]
A Vim 9 release is imminent.  It would be nice if we could include a more recent version of this project as the included files are very old.

@petdance, if you agree in principal but are busy I can update Bram with your approval.

Thanks,
Doug

**Comment by petdance** [comment]
I agree it would be nice. What do I/you/we need to do?

**Comment by petdance** [comment]
And thank you for being on top of this. <3

**Comment by dkearns** [comment]
Someone just needs to either email the relevant runtime files to Bram directly or create a PR against the [Vim repo](https://github.com/vim/vim).

**Comment by petdance** [comment]
Yes, please, start a PR against the vim repo. If I remember correctly, last time I send files to Bram many years ago I think he didn't take them because he didn't like some of the changes, so starting sooner than later would probably be good.  Thank you.

**Comment by dkearns** [comment]
OK

**Comment by dkearns** [comment]
I've sent the latest change as an email to Bram.

**Comment by rabbiveesh** [comment]
#249 is a duplicate

**Comment by petdance** [comment]
Thanks. I'll close it when I close this one.
