### ISSUE TITLE
Look at what's new in vim 9

### ISSUE THREAD

**Issue by petdance** [vim-perl/vim-perl#323]
Are there new features we can use?

What about moving to Vim9 script for the speed improvements?

> Compiled [functions](https://vimhelp.org/eval.txt.html#functions) [a](https://vimhelp.org/insert.txt.html#a)re introduced which allow for a large speed improvement.  You can expect around ten times faster execution, or even more.  The price to pay [is](https://vimhelp.org/motion.txt.html#is) that [Vim9](https://vimhelp.org/vim9.txt.html#Vim9) [script](https://vimhelp.org/usr_41.txt.html#script) [is](https://vimhelp.org/motion.txt.html#is) not backwards compatible.

See https://vimhelp.org/version9.txt.html

**Comment by clscott** [comment]
This appears to be a dupe of #322

**Comment by petdance** [comment]
Ooops thanks.
