### ISSUE TITLE
indent/raku.vim bug

### ISSUE THREAD

**Issue by Heptite** [vim-perl/vim-perl#328]
# Description of issue

indent/raku.vim doesn't properly indent when &shiftwidth is is 0 (which in newer versions of Vim means to use the value of &tabstop).

# Solution

Replace all occurrences of &sw in the indent/raku.vim file with shiftwidth()

**Comment by petdance** [comment]
Raku stuff is in its own project. Looks like https://github.com/Raku/vim-raku would be a good place to start, but I don't know for sure.

**Comment by Heptite** [comment]
Oops, I copied and pasted the URL from the indent/raku.vim file without paying attention to which repository it took me to. Thanks for pointing me in the right direction.

**Comment by petdance** [comment]
Then it looks like you could provide an issue for them to change their URLs, too. :-)
