### ISSUE TITLE
ftplugin/pod.vim unmaps ]] twice but does not unmap [[

### ISSUE THREAD

**Issue by gary-calderadev** [vim-perl/vim-perl#332]
# Description of issue

The ftplugin/pod.vim script maps all four combinations of [ and ]. There are two identical lines that unmap ]] but there is no unmapping of [[.

# Output of `vim --version`

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 15 2023 23:08:32)
Included patches: 1-1636
Compiled by gary@epicurus
Normal version with GTK3 GUI.  Features included (+) or not (-):
+acl               +cryptv            +fork()            +modify_fname      +persistent_undo   -sun_workshop      +viminfo
-arabic            +cscope            +gettext           +mouse             +popupwin          +syntax            +virtualedit
+autocmd           +cursorbind        -hangul_input      +mouseshape        +postscript        +tag_binary        +visual
+autochdir         +cursorshape       +iconv             +mouse_dec         +printer           -tag_old_static    +visualextra
-autoservername    +dialog_con_gui    +insert_expand     +mouse_gpm         -profile           -tag_any_white     +vreplace
+balloon_eval      +diff              +ipv6              -mouse_jsbterm     -python            -tcl               +wildignore
-balloon_eval_term +digraphs          +job               +mouse_netterm     -python3           +termguicolors     +wildmenu
+browse            +dnd               +jumplist          +mouse_sgr         +quickfix          -terminal          +windows
++builtin_terms    -ebcdic            -keymap            -mouse_sysmouse    +reltime           +terminfo          +writebackup
+byte_offset       -emacs_tags        +lambda            +mouse_urxvt       -rightleft         +termresponse      +X11
+channel           +eval              -langmap           +mouse_xterm       -ruby              +textobjects       -xfontset
+cindent           +ex_extra          +libcall           +multi_byte        +scrollbind        +textprop          +xim
+clientserver      +extra_search      +linebreak         +multi_lang        +signs             +timers            +xpm
+clipboard         -farsi             +lispindent        -mzscheme          +smartindent       +title             +xsmp_interact
+cmdline_compl     +file_in_path      +listcmds          +netbeans_intg     -sodium            +toolbar           +xterm_clipboard
+cmdline_hist      +find_in_path      +localmap          +num64             -sound             +user_commands     -xterm_save
+cmdline_info      +float             -lua               +packages          +spell             +vartabs           
+comments          +folding           +menu              +path_extra        +startuptime       +vertsplit         
+conceal           -footer            +mksession         -perl              +statusline        +vim9script        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g3 -Wno-deprecated-declarations -DFEAT_MOUSE_SGR -DFEAT_VARTABS -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lacl -lattr -lgpm

**Comment by petdance** [comment]
I'll need someone to submit a patch for this because I don't know what the fix here would be.

**Comment by gary-calderadev** [comment]
Hi Andy,

Attached is a patch.

Regards,
Gary
________________________________

**Comment by petdance** [comment]
File attachments don't come through when replying to threads. You'll need to paste it in the web page at https://github.com/vim-perl/vim-perl/issues/332 or email it to me at andy@petdance.com.

**Comment by petdance** [comment]
Here's what Gary sent.

```
diff --git a/runtime/ftplugin/pod.vim b/runtime/ftplugin/pod.vim
index 2a905ab35..cfa68a8ef 100644
--- a/runtime/ftplugin/pod.vim
+++ b/runtime/ftplugin/pod.vim
@@ -5,7 +5,7 @@
 " Homepage:      https://github.com/vim-perl/vim-perl
 " Bugs/requests: https://github.com/vim-perl/vim-perl/issues
 " License:       Vim License (see :help license)
-" Last Change:   2021 Oct 19
+" Last Change:   2023 Jun 25
 
 if exists("b:did_ftplugin")
     finish
@@ -61,7 +61,7 @@ if !exists("no_plugin_maps") && !exists("no_pod_maps")
   let b:undo_ftplugin .=
         \ " | silent! exe 'nunmap <buffer> ]]' | silent! exe 'vunmap <buffer> ]]'" .
         \ " | silent! exe 'nunmap <buffer> ][' | silent! exe 'vunmap <buffer> ]['" .
-        \ " | silent! exe 'nunmap <buffer> ]]' | silent! exe 'vunmap <buffer> ]]'" .
+        \ " | silent! exe 'nunmap <buffer> [[' | silent! exe 'vunmap <buffer> [['" .
         \ " | silent! exe 'nunmap <buffer> []' | silent! exe 'vunmap <buffer> []'"
 endif
 ```

**Comment by petdance** [comment]
I've updated it. Thanks for the patch.

1eea8d74fd4b1e475b6054d77ac031aa21543d5d
