### ISSUE TITLE
Update vim-perl to be included in Vim 9.1

### ISSUE THREAD

**Issue by dkearns** [vim-perl/vim-perl#336]
There's a possibly imminent 9.1 release so we should update the mother ship.

I can do that, if you like, @petdance.

**Comment by petdance** [comment]
> I can do that, if you like, @petdance.

Yes, please do.

How have things changed now with Bram's passing? Has someone taken his place? Multiple people?

**Comment by dkearns** [comment]
Done.

Thankfully, one of the long-time maintainers has kept things rolling and some other significant contributors have increased their input.
