### ISSUE TITLE
security fix from the Vim project

### ISSUE THREAD

**Issue by chrisbra** [vim-perl/vim-perl#337]
Hi,
please be aware of the following change I made in the Vim project to prevent executing the perl command line tool on windows from the current directory.

See https://github.com/vim/vim/commit/816fbcc262687b81fc46f82f7bbeb1453addfe0c and https://huntr.dev/bounties/e1ce0995-4df4-4dec-9cd7-3136ac3e8e71/

You may want to check it and include the fix in your version.

I am also thinking to make running the perl program from the ftplugin opt-in by default, to make sure nothing is executed unexpectedly by the user. What do you think? 

Thanks,
Chris

**Comment by petdance** [comment]
I've applied the one change in ftplugin/perl.vim.  Thank you.  f59a1610b928bd349c4a471804e38960e001a1af

**Comment by chrisbra** [comment]
Note: in the meantime, there were a few more refinements:
- https://github.com/vim/vim/commit/f7ac0ef5098856bedca26e7073594a407c05636f
- https://github.com/vim/vim/commit/67c951df4c95981c716eeedb1b102d9668549e65
