### ISSUE TITLE
Correct commentstring for xs files

### ISSUE THREAD

**Issue by sohamshanbhag** [vim-perl/vim-perl#343]
This issue is in regards to [this](https://github.com/neovim/neovim/issues/29079) issue.

---

I had raised an issue on neovim regarding changing the default commentstring for C/C++ files. Since `xs` files depends on this, I wanted to confirm what the correct commentstring is. Is `// %s` or `/* %s */` the correct commentstring for `xs` files? [This](https://perldoc.perl.org/perlxs#Inserting-POD,-Comments-and-C-Preprocessor-Directives) link says that the correct commentstring should be `# %s`, while the present one is `/*%s*/` (in neovim and vim)? Moreover, both `//` and `/**/` are shown as comments when in vim.

I wanted to confirm since I do not have experience with perl or xs files.

**Comment by petdance** [comment]
As far as I know, xs files are effectively C files with some preprocessor goodness.  If there's not a problem, I don't see any reason to change anything.

**Comment by sohamshanbhag** [comment]
I see, thanks for the clarification. I was confused due to the information [here](https://perldoc.perl.org/perlxs#Inserting-POD,-Comments-and-C-Preprocessor-Directives) and wanted to confirm it.
