### ISSUE TITLE
[perl6.vim] Improper highlighting after lines with odd number of quotes

### ISSUE THREAD

**Issue by svatsan** [vim-perl/vim-perl#51]
Vim syntax highlighting is not correct with lines after those containing odd number of quotes (single, in this case)

Here's a link to an example: 
https://github.com/masak/yapsi/blob/master/lib/Yapsi.pm#L785

PS: I currently work around this by inserting another single quote on the same line inside a comment, like so `# ' `

**Comment by hinrik** [comment]
This has been fixed.
