### ISSUE TITLE
Curly braces inside q// match against real curly braces

### ISSUE THREAD

**Issue by shlomif** [vim-perl/vim-perl#86]
In this file:

http://www.shlomifish.org/Files/files/code/vim-perl-issue-curly-braces-inside-q.txt

One cannot match the very first curly brace (at the start of line 2) because the ones inside the q/../ qualify as such. I am using commit b94578ec3e0633592820c3a10c12930b80560193 .

Please look into it.

Regards,

-- Shlomi Fish

P.S: I discovered that one cannot attach files to issues of GitHub's issue tracker:

http://stackoverflow.com/questions/10963205/how-to-attach-file-to-a-github-issue

I guess it can suck a lot less.

**Comment by SSH93** [comment]
Vb
