### ISSUE TITLE
turn off auto line breaks when textwidth is set

### ISSUE THREAD

**Issue by gokcehan** [vim-perl/vim-perl#91]
default `formatoptions` is set to `tcq` and `ftplugin/perl.vim` has a line:

```
setlocal formatoptions+=crq
```

making it `tcrq` in the end. this way with `t` option included, vim automatically breaks a line if you set the `textwidth` option. most other filetypes exlude this with a `set fo-=t` as it's hardly any desirable when writing code. the following line is from `ftplugin/c.vim`:

```
setlocal fo-=t fo+=croql
```

and I think makes much more sense as default. the reason this is missing is probably because it doesn't do the break when `textwidth` is set to `0` which is the default value. but I believe nowadays many users are setting a `textwidth` in order to format comments and use `colorcolumn` options..

**Comment by rjbs** [comment]
…but I want to keep `t` in my `formatoptions`.  What's the best/preferred way to override this change?  I'm guessing: add `fo += t` to my  `after/ftplugin/perl.vim`

**Comment by hoelzro** [comment]
@rjbs That should do it!
