### ISSUE TITLE
Add apostrophe to &iskeyword

### ISSUE THREAD

**Issue by hoelzro** [vim-perl/vim-perl#97]
Simply appending ,' to where we set iskeyword isn't working, so I'm deferring this for now, until I have time to investigate, or until someone with better Vim-fu comes along. =)

**Comment by hinrik** [comment]
Apostrophe was added to 'iskeyword' back in f7f84ea, which did indeed break things. But as of 15e7d34, the issues are fixed.

**Comment by hinrik** [comment]
Oh actually, I meant dash. Still no apostrope.

**Comment by hinrik** [comment]
I just added apostrophe to 'iskeyword' in e95d42b. Tell me if you find any issues with it.
